# This pipeline is designed to run as a cron-job and not triggered by every build - once a day is probably enough

jobs:

- job: 'docs_websites_linkchecker'

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:

  - script: |
      echo "Installing prerequisites"
      sudo apt install w3c-linkchecker
      echo "Entering link checker"
      cd checklink
    displayName: 'Installing prerequisites, prepare for checking'
    continueOnError: false

  - script: |
      echo "Testing docs-dev"
      ./checklink-docs-dev.sh
      if [[ ! -f checklink-docs-dev.log ]]; then echo "Program didn't run"; false; fi
      if [[   -s checklink-docs-dev.log ]]; then echo "Got broken links"; cat checklink-docs-dev.log; false; else echo "No broken links were found"; fi
    displayName: 'link checker for docs-dev.fast.ai'
    continueOnError: true

  - script: |
      echo "Testing docs"
      ls -l checklink
      if [[ ! -f checklink-docs.log ]]; then echo "Program didn't run"; false; fi
      if [[   -s checklink-docs.log ]]; then echo "Got broken links"; cat checklink-docs.log; false; else echo "No broken links were found"; fi
    displayName: 'link checker for docs.fast.ai'
    continueOnError: true
