# This pipeline is designed to run as a cron-job and not triggered by every build - once a day is probably enough

jobs:

- job: 'docs_websites_linkchecker'

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:

  - script: |
      echo "Installing prerequisites"
      sudo apt install w3c-linkchecker
      echo "Entering link checker"
      cd checklink
    displayName: 'Installing prerequisites, prepare for checking'
    continueOnError: false

  - script: |
      echo "Testing docs-dev"
      ./checklink-docs-dev.sh
      ./run-checker.sh docs-dev
    displayName: 'link checker for docs-dev.fast.ai'
    continueOnError: true

  - script: |
      echo "Testing docs"
      ./checklink-docs.sh
      ./run-checker.sh docs
    displayName: 'link checker for docs.fast.ai'
    continueOnError: true
